// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwhwmsupehiixxhpvofw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aHdtc3VwZWhpaXh4aHB2b2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjIzMTQsImV4cCI6MjA1OTE5ODMxNH0.90r2drJlzUCeU0PszPwO68A0-KGpaPR9YbK8QkujlqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);